#!/bin/bash
#
# Generated by: Claude-Sonnet 4.5
# Date: November 23, 2025
#

# Wrapper script to set up X11 environment for x11auto-lid.sh
# This runs as root and finds the active X session

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Function to find the active X display and user
find_x_session() {
    local display=":0"
    local xauth=""
    local xuser=""
    
    # Find the user running X11 session (same logic as x11auto.udev.sh)
    xuser=$(who | grep -E "tty[0-9]+ .+\(:0\)" | awk '{print $1}' | head -1)
    
    # Alternative: check for users with DISPLAY :0
    if [ -z "$xuser" ]; then
        xuser=$(ps aux | grep "X.*:0" | grep -v grep | awk '{print $1}' | head -1)
    fi
    
    # If still no user found, exit with error
    if [ -z "$xuser" ]; then
        echo "[$(date)] ERROR: Could not determine X11 user"
        exit 1
    fi
    
    # Find XAUTHORITY file for the user
    local uid=$(id -u "$xuser" 2>/dev/null || echo "1000")
    
    # Try common XAUTHORITY locations
    if [ -f "/run/user/$uid/gdm/Xauthority" ]; then
        xauth="/run/user/$uid/gdm/Xauthority"
    elif [ -f "/home/$xuser/.Xauthority" ]; then
        xauth="/home/$xuser/.Xauthority"
    fi
    
    export DISPLAY="$display"
    if [ -n "$xauth" ] && [ -f "$xauth" ]; then
        export XAUTHORITY="$xauth"
    fi
    
    echo "Detected X session: DISPLAY=$DISPLAY XAUTHORITY=${XAUTHORITY:-none} USER=${xuser:-unknown}"
}

# Find and set up X session environment
find_x_session

# Run the main script
exec "$SCRIPT_DIR/x11auto-lid.sh"


